import dotenv from "dotenv";

dotenv.config();
export const ENV = {
  PORT: process.env.PORT,
  DOCTOR_DASHBOARD_URL: process.env.DOCTOR_DASHBOARD_URL,
  PHARMACY_DASHBOARD_URL: process.env.PHARMACY_DASHBOARD_URL,
  ADMIN_DASHBOARD_URL: process.env.ADMIN_DASHBOARD_URL,
  PATIENT_APP_URL: process.env.PATIENT_APP_URL,
  DB_URI: process.env.DB_URI,
  NODE_ENV: process.env.NODE_ENV,
  CLERK_WEBHOOK_SECRET: process.env.CLERK_WEBHOOK_SECRET,
  CLERK_PUBLISHABLE_KEY: process.env.CLERK_PUBLISHABLE_KEY,
  CLERK_SECRET_KEY: process.env.CLERK_SECRET_KEY,
  CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET,
};

